import { applyOpeningSupplement } from "./openingLocalizationSupplement";

const SUPPORTED = ["en","es","fr","de","pt","ru","zh","vi","hi","mr","pl"] as const;
type Lang = typeof SUPPORTED[number];

const FAMILIES: Record<Lang, Record<string,string>> = {
  en: {},
  es: {
    "Ruy Lopez":"Apertura española","Italian Game":"Apertura italiana","Scotch Game":"Apertura escocesa","Ponziani Opening":"Apertura Ponziani","Vienna Game":"Apertura vienesa","Four Knights Game":"Apertura de los cuatro caballos","King's Gambit":"Gambito de rey","Queen's Gambit":"Gambito de dama","London System":"Sistema Londres","Catalan Opening":"Apertura catalana","Trompowsky Attack":"Ataque Trompowsky","Colle System":"Sistema Colle","Jobava London System":"Sistema Londres Jobava","Sicilian Defense":"Defensa siciliana","French Defense":"Defensa francesa","Caro-Kann Defense":"Defensa Caro-Kann","Scandinavian Defense":"Defensa escandinava","Pirc Defense":"Defensa Pirc","Modern Defense":"Defensa moderna","Alekhine Defense":"Defensa Alekhine","King's Indian Defense":"Defensa india de rey","Queen's Indian Defense":"Defensa india de dama","Nimzo-Indian Defense":"Defensa nimzoindia","Bogo-Indian Defense":"Defensa bogoindia","Grünfeld Defense":"Defensa Grünfeld","Slav Defense":"Defensa eslava","Semi-Slav Defense":"Defensa semieslava","Dutch Defense":"Defensa holandesa","Benoni Defense":"Defensa Benoni","Benko Gambit":"Gambito Benko","Queen's Gambit Declined":"Gambito de dama declinado","Queen's Gambit Accepted":"Gambito de dama aceptado","English Opening":"Apertura inglesa","Réti Opening":"Apertura Réti","Bird Opening":"Apertura Bird","King's Indian Attack":"Ataque indio de rey","Stonewall Attack":"Ataque Stonewall","Queen's Pawn Game":"Juego del peón de dama"
  },
  fr: {
    "Ruy Lopez":"Partie espagnole","Italian Game":"Partie italienne","Scotch Game":"Partie écossaise","Ponziani Opening":"Ouverture Ponziani","Vienna Game":"Partie viennoise","Four Knights Game":"Partie des quatre cavaliers","King's Gambit":"Gambit du roi","Queen's Gambit":"Gambit dame","London System":"Système de Londres","Catalan Opening":"Ouverture catalane","Trompowsky Attack":"Attaque Trompowsky","Colle System":"Système Colle","Jobava London System":"Système de Londres Jobava","Sicilian Defense":"Défense sicilienne","French Defense":"Défense française","Caro-Kann Defense":"Défense Caro-Kann","Scandinavian Defense":"Défense scandinave","Pirc Defense":"Défense Pirc","Modern Defense":"Défense moderne","Alekhine Defense":"Défense Alekhine","King's Indian Defense":"Défense est-indienne","Queen's Indian Defense":"Défense ouest-indienne","Nimzo-Indian Defense":"Défense nimzo-indienne","Bogo-Indian Defense":"Défense bogo-indienne","Grünfeld Defense":"Défense Grünfeld","Slav Defense":"Défense slave","Semi-Slav Defense":"Défense semi-slave","Dutch Defense":"Défense hollandaise","Benoni Defense":"Défense Benoni","Benko Gambit":"Gambit Benko","Queen's Gambit Declined":"Gambit dame refusé","Queen's Gambit Accepted":"Gambit dame accepté","English Opening":"Ouverture anglaise","Réti Opening":"Ouverture Réti","Bird Opening":"Ouverture Bird","King's Indian Attack":"Attaque est-indienne","Stonewall Attack":"Attaque Stonewall","Queen's Pawn Game":"Début du pion dame"
  },
  de: {
    "Ruy Lopez":"Spanische Partie","Italian Game":"Italienische Partie","Scotch Game":"Schottische Partie","Ponziani Opening":"Ponziani-Eröffnung","Vienna Game":"Wiener Partie","Four Knights Game":"Vierspringerspiel","King's Gambit":"Königsgambit","Queen's Gambit":"Damengambit","London System":"Londoner System","Catalan Opening":"Katalanische Eröffnung","Trompowsky Attack":"Trompowsky-Angriff","Colle System":"Colle-System","Jobava London System":"Jobava-London-System","Sicilian Defense":"Sizilianische Verteidigung","French Defense":"Französische Verteidigung","Caro-Kann Defense":"Caro-Kann-Verteidigung","Scandinavian Defense":"Skandinavische Verteidigung","Pirc Defense":"Pirc-Verteidigung","Modern Defense":"Moderne Verteidigung","Alekhine Defense":"Aljechin-Verteidigung","King's Indian Defense":"Königsindische Verteidigung","Queen's Indian Defense":"Damenindische Verteidigung","Nimzo-Indian Defense":"Nimzo-Indische Verteidigung","Bogo-Indian Defense":"Bogo-Indische Verteidigung","Grünfeld Defense":"Grünfeld-Indische Verteidigung","Slav Defense":"Slawische Verteidigung","Semi-Slav Defense":"Halbslawische Verteidigung","Dutch Defense":"Holländische Verteidigung","Benoni Defense":"Benoni-Verteidigung","Benko Gambit":"Benko-Gambit","Queen's Gambit Declined":"Abgelehntes Damengambit","Queen's Gambit Accepted":"Angenommenes Damengambit","English Opening":"Englische Eröffnung","Réti Opening":"Réti-Eröffnung","Bird Opening":"Bird-Eröffnung","King's Indian Attack":"Königsindischer Angriff","Stonewall Attack":"Stonewall-Angriff","Queen's Pawn Game":"Damenbauernspiel"
  },
  pt: {
    "Ruy Lopez":"Abertura espanhola","Italian Game":"Abertura italiana","Scotch Game":"Abertura escocesa","Ponziani Opening":"Abertura Ponziani","Vienna Game":"Abertura vienense","Four Knights Game":"Abertura dos quatro cavalos","King's Gambit":"Gambito do rei","Queen's Gambit":"Gambito da dama","London System":"Sistema Londres","Catalan Opening":"Abertura catalã","Trompowsky Attack":"Ataque Trompowsky","Colle System":"Sistema Colle","Jobava London System":"Sistema Londres Jobava","Sicilian Defense":"Defesa siciliana","French Defense":"Defesa francesa","Caro-Kann Defense":"Defesa Caro-Kann","Scandinavian Defense":"Defesa escandinava","Pirc Defense":"Defesa Pirc","Modern Defense":"Defesa moderna","Alekhine Defense":"Defesa Alekhine","King's Indian Defense":"Defesa índia do rei","Queen's Indian Defense":"Defesa índia da dama","Nimzo-Indian Defense":"Defesa nimzoíndia","Bogo-Indian Defense":"Defesa bogoíndia","Grünfeld Defense":"Defesa Grünfeld","Slav Defense":"Defesa eslava","Semi-Slav Defense":"Defesa semieslava","Dutch Defense":"Defesa holandesa","Benoni Defense":"Defesa Benoni","Benko Gambit":"Gambito Benko","Queen's Gambit Declined":"Gambito da dama recusado","Queen's Gambit Accepted":"Gambito da dama aceito","English Opening":"Abertura inglesa","Réti Opening":"Abertura Réti","Bird Opening":"Abertura Bird","King's Indian Attack":"Ataque índio do rei","Stonewall Attack":"Ataque Stonewall","Queen's Pawn Game":"Jogo do peão da dama"
  },
  ru: {
    "Ruy Lopez":"Испанская партия","Italian Game":"Итальянская партия","Scotch Game":"Шотландская партия","Ponziani Opening":"Дебют Понциани","Vienna Game":"Венская партия","Four Knights Game":"Дебют четырёх коней","King's Gambit":"Королевский гамбит","Queen's Gambit":"Ферзевый гамбит","London System":"Лондонская система","Catalan Opening":"Каталонское начало","Trompowsky Attack":"Атака Тромповского","Colle System":"Система Колле","Jobava London System":"Лондонская система Джобава","Sicilian Defense":"Сицилианская защита","French Defense":"Французская защита","Caro-Kann Defense":"Защита Каро-Канн","Scandinavian Defense":"Скандинавская защита","Pirc Defense":"Защита Пирца","Modern Defense":"Современная защита","Alekhine Defense":"Защита Алехина","King's Indian Defense":"Староиндийская защита","Queen's Indian Defense":"Новоиндийская защита","Nimzo-Indian Defense":"Защита Нимцовича","Bogo-Indian Defense":"Защита Боголюбова","Grünfeld Defense":"Защита Грюнфельда","Slav Defense":"Славянская защита","Semi-Slav Defense":"Полуславянская защита","Dutch Defense":"Голландская защита","Benoni Defense":"Защита Бенони","Benko Gambit":"Гамбит Бенко","Queen's Gambit Declined":"Отказанный ферзевый гамбит","Queen's Gambit Accepted":"Принятый ферзевый гамбит","English Opening":"Английское начало","Réti Opening":"Дебют Рети","Bird Opening":"Дебют Бёрда","King's Indian Attack":"Староиндийское нападение","Stonewall Attack":"Атака Стоунволл","Queen's Pawn Game":"Дебют ферзевых пешек"
  },
  zh: {
    "Ruy Lopez":"西班牙开局","Italian Game":"意大利开局","Scotch Game":"苏格兰开局","Ponziani Opening":"庞齐亚尼开局","Vienna Game":"维也纳开局","Four Knights Game":"四马开局","King's Gambit":"王翼弃兵","Queen's Gambit":"后翼弃兵","London System":"伦敦体系","Catalan Opening":"加泰罗尼亚开局","Trompowsky Attack":"特罗姆普夫斯基进攻","Colle System":"科勒体系","Jobava London System":"乔巴瓦伦敦体系","Sicilian Defense":"西西里防御","French Defense":"法兰西防御","Caro-Kann Defense":"卡罗-康防御","Scandinavian Defense":"斯堪的纳维亚防御","Pirc Defense":"皮尔茨防御","Modern Defense":"现代防御","Alekhine Defense":"阿廖欣防御","King's Indian Defense":"王翼印度防御","Queen's Indian Defense":"后翼印度防御","Nimzo-Indian Defense":"尼姆佐-印度防御","Bogo-Indian Defense":"博戈-印度防御","Grünfeld Defense":"格林菲尔德防御","Slav Defense":"斯拉夫防御","Semi-Slav Defense":"半斯拉夫防御","Dutch Defense":"荷兰防御","Benoni Defense":"贝诺尼防御","Benko Gambit":"本科弃兵","Queen's Gambit Declined":"拒后翼弃兵","Queen's Gambit Accepted":"接受后翼弃兵","English Opening":"英格兰开局","Réti Opening":"列蒂开局","Bird Opening":"伯德开局","King's Indian Attack":"王翼印度进攻","Stonewall Attack":"石墙进攻","Queen's Pawn Game":"后兵开局"
  },
  vi: {
    "Ruy Lopez":"Khai cuộc Tây Ban Nha","Italian Game":"Ván cờ Ý","Scotch Game":"Ván cờ Scotland","Ponziani Opening":"Khai cuộc Ponziani","Vienna Game":"Ván cờ Vienna","Four Knights Game":"Khai cuộc Bốn Mã","King's Gambit":"Gambit Vua","Queen's Gambit":"Gambit Hậu","London System":"Hệ thống London","Catalan Opening":"Khai cuộc Catalan","Trompowsky Attack":"Tấn công Trompowsky","Colle System":"Hệ thống Colle","Jobava London System":"Hệ thống London Jobava","Sicilian Defense":"Phòng thủ Sicilia","French Defense":"Phòng thủ Pháp","Caro-Kann Defense":"Phòng thủ Caro-Kann","Scandinavian Defense":"Phòng thủ Scandinavia","Pirc Defense":"Phòng thủ Pirc","Modern Defense":"Phòng thủ Hiện đại","Alekhine Defense":"Phòng thủ Alekhine","King's Indian Defense":"Phòng thủ Ấn Độ Vua","Queen's Indian Defense":"Phòng thủ Ấn Độ Hậu","Nimzo-Indian Defense":"Phòng thủ Nimzo-Ấn Độ","Bogo-Indian Defense":"Phòng thủ Bogo-Ấn Độ","Grünfeld Defense":"Phòng thủ Grünfeld","Slav Defense":"Phòng thủ Slav","Semi-Slav Defense":"Phòng thủ Bán Slav","Dutch Defense":"Phòng thủ Hà Lan","Benoni Defense":"Phòng thủ Benoni","Benko Gambit":"Gambit Benko","Queen's Gambit Declined":"Gambit Hậu từ chối","Queen's Gambit Accepted":"Gambit Hậu chấp nhận","English Opening":"Khai cuộc Anh","Réti Opening":"Khai cuộc Réti","Bird Opening":"Khai cuộc Bird","King's Indian Attack":"Tấn công Ấn Độ Vua","Stonewall Attack":"Tấn công Stonewall","Queen's Pawn Game":"Ván cờ Tốt Hậu"
  },
  hi: {
    "Ruy Lopez":"स्पेनिश ओपनिंग","Italian Game":"इटालियन गेम","Scotch Game":"स्कॉच गेम","Ponziani Opening":"पोंज़ियानी ओपनिंग","Vienna Game":"वियना गेम","Four Knights Game":"फोर नाइट्स गेम","King's Gambit":"किंग्स गैम्बिट","Queen's Gambit":"क्वीन्स गैम्बिट","London System":"लंदन सिस्टम","Catalan Opening":"कैटलान ओपनिंग","Trompowsky Attack":"ट्रोम्पोव्स्की अटैक","Colle System":"कोले सिस्टम","Jobava London System":"जोबावा लंदन सिस्टम","Sicilian Defense":"सिसिलियन डिफेंस","French Defense":"फ्रेंच डिफेंस","Caro-Kann Defense":"कारो-कान डिफेंस","Scandinavian Defense":"स्कैंडिनेवियन डिफेंस","Pirc Defense":"पिर्क डिफेंस","Modern Defense":"मॉडर्न डिफेंस","Alekhine Defense":"अलेखिन डिफेंस","King's Indian Defense":"किंग्स इंडियन डिफेंस","Queen's Indian Defense":"क्वीन्स इंडियन डिफेंस","Nimzo-Indian Defense":"निम्ज़ो-इंडियन डिफेंस","Bogo-Indian Defense":"बोगो-इंडियन डिफेंस","Grünfeld Defense":"ग्रुनफेल्ड डिफेंस","Slav Defense":"स्लाव डिफेंस","Semi-Slav Defense":"सेमी-स्लाव डिफेंस","Dutch Defense":"डच डिफेंस","Benoni Defense":"बेनोनी डिफेंस","Benko Gambit":"बेंको गैम्बिट","Queen's Gambit Declined":"क्वीन्स गैम्बिट डिक्लाइंड","Queen's Gambit Accepted":"क्वीन्स गैम्बिट एक्सेप्टेड","English Opening":"इंग्लिश ओपनिंग","Réti Opening":"रेती ओपनिंग","Bird Opening":"बर्ड ओपनिंग","King's Indian Attack":"किंग्स इंडियन अटैक","Stonewall Attack":"स्टोनवॉल अटैक","Queen's Pawn Game":"क्वीन्स पॉन गेम"
  },
  mr: {
    "Ruy Lopez":"स्पॅनिश ओपनिंग","Italian Game":"इटालियन गेम","Scotch Game":"स्कॉच गेम","Ponziani Opening":"पोंझियानी ओपनिंग","Vienna Game":"व्हिएन्ना गेम","Four Knights Game":"फोर नाइट्स गेम","King's Gambit":"किंग्स गॅम्बिट","Queen's Gambit":"क्वीन्स गॅम्बिट","London System":"लंडन सिस्टीम","Catalan Opening":"कॅटलान ओपनिंग","Trompowsky Attack":"ट्रोम्पोव्स्की अटॅक","Colle System":"कोले सिस्टीम","Jobava London System":"जोबावा लंडन सिस्टीम","Sicilian Defense":"सिसिलियन डिफेन्स","French Defense":"फ्रेंच डिफेन्स","Caro-Kann Defense":"कारो-कान डिफेन्स","Scandinavian Defense":"स्कँडिनेव्हियन डिफेन्स","Pirc Defense":"पिर्क डिफेन्स","Modern Defense":"मॉडर्न डिफेन्स","Alekhine Defense":"अलेखिन डिफेन्स","King's Indian Defense":"किंग्स इंडियन डिफेन्स","Queen's Indian Defense":"क्वीन्स इंडियन डिफेन्स","Nimzo-Indian Defense":"निम्झो-इंडियन डिफेन्स","Bogo-Indian Defense":"बोगो-इंडियन डिफेन्स","Grünfeld Defense":"ग्रुनफेल्ड डिफेन्स","Slav Defense":"स्लाव डिफेन्स","Semi-Slav Defense":"सेमी-स्लाव डिफेन्स","Dutch Defense":"डच डिफेन्स","Benoni Defense":"बेनोनी डिफेन्स","Benko Gambit":"बेंको गॅम्बिट","Queen's Gambit Declined":"क्वीन्स गॅम्बिट डिक्लाइंड","Queen's Gambit Accepted":"क्वीन्स गॅम्बिट अॅक्सेप्टेड","English Opening":"इंग्लिश ओपनिंग","Réti Opening":"रेती ओपनिंग","Bird Opening":"बर्ड ओपनिंग","King's Indian Attack":"किंग्स इंडियन अटॅक","Stonewall Attack":"स्टोनवॉल अटॅक","Queen's Pawn Game":"क्वीन्स पॉन गेम"
  },
  pl: {
    "Ruy Lopez":"Partia hiszpańska","Italian Game":"Partia włoska","Scotch Game":"Partia szkocka","Ponziani Opening":"Debiut Ponzianiego","Vienna Game":"Partia wiedeńska","Four Knights Game":"Gra czterech skoczków","King's Gambit":"Gambit królewski","Queen's Gambit":"Gambit hetmański","London System":"System londyński","Catalan Opening":"Otwarcie katalońskie","Trompowsky Attack":"Atak Trompowskiego","Colle System":"System Colle","Jobava London System":"System londyński Jobavy","Sicilian Defense":"Obrona sycylijska","French Defense":"Obrona francuska","Caro-Kann Defense":"Obrona Caro-Kann","Scandinavian Defense":"Obrona skandynawska","Pirc Defense":"Obrona Pirca","Modern Defense":"Obrona nowoczesna","Alekhine Defense":"Obrona Alechina","King's Indian Defense":"Obrona królewsko-indyjska","Queen's Indian Defense":"Obrona hetmańsko-indyjska","Nimzo-Indian Defense":"Obrona Nimzo-indyjska","Bogo-Indian Defense":"Obrona Bogo-indyjska","Grünfeld Defense":"Obrona Grünfelda","Slav Defense":"Obrona słowiańska","Semi-Slav Defense":"Obrona półsłowiańska","Dutch Defense":"Obrona holenderska","Benoni Defense":"Obrona Benoni","Benko Gambit":"Gambit Benko","Queen's Gambit Declined":"Nieprzyjęty gambit hetmański","Queen's Gambit Accepted":"Przyjęty gambit hetmański","English Opening":"Otwarcie angielskie","Réti Opening":"Otwarcie Rétiego","Bird Opening":"Otwarcie Birda","King's Indian Attack":"Atak królewsko-indyjski","Stonewall Attack":"Atak Stonewall","Queen's Pawn Game":"Gra pionem hetmańskim"
  }
};

const PHRASES: Record<Lang, Array<[string,string]>> = {
  en: [],
  es: [["Classical Variation","Variante clásica"],["Main Line","Línea principal"],["Exchange Variation","Variante del cambio"],["Advance Variation","Variante del avance"],["Accepted","Aceptado"],["Declined","Declinado"],["Modern Variation","Variante moderna"],["Normal Variation","Variante normal"],["Variation","Variante"],["Defense","Defensa"],["Defence","Defensa"],["Opening","Apertura"],["Attack","Ataque"],["Gambit","Gambito"],["System","Sistema"],["Game","Partida"],["Line","Línea"]],
  fr: [["Classical Variation","Variante classique"],["Main Line","Ligne principale"],["Exchange Variation","Variante d'échange"],["Advance Variation","Variante d'avance"],["Accepted","Accepté"],["Declined","Refusé"],["Modern Variation","Variante moderne"],["Normal Variation","Variante normale"],["Variation","Variante"],["Defense","Défense"],["Defence","Défense"],["Opening","Ouverture"],["Attack","Attaque"],["Gambit","Gambit"],["System","Système"],["Game","Partie"],["Line","Ligne"]],
  de: [["Classical Variation","Klassische Variante"],["Main Line","Hauptvariante"],["Exchange Variation","Abtauschvariante"],["Advance Variation","Vorstoßvariante"],["Accepted","Angenommen"],["Declined","Abgelehnt"],["Modern Variation","Moderne Variante"],["Normal Variation","Normale Variante"],["Variation","Variante"],["Defense","Verteidigung"],["Defence","Verteidigung"],["Opening","Eröffnung"],["Attack","Angriff"],["Gambit","Gambit"],["System","System"],["Game","Partie"],["Line","Variante"]],
  pt: [["Classical Variation","Variante clássica"],["Main Line","Linha principal"],["Exchange Variation","Variante da troca"],["Advance Variation","Variante do avanço"],["Accepted","Aceito"],["Declined","Recusado"],["Modern Variation","Variante moderna"],["Normal Variation","Variante normal"],["Variation","Variante"],["Defense","Defesa"],["Defence","Defesa"],["Opening","Abertura"],["Attack","Ataque"],["Gambit","Gambito"],["System","Sistema"],["Game","Partida"],["Line","Linha"]],
  ru: [["Classical Variation","Классический вариант"],["Main Line","Главная линия"],["Exchange Variation","Разменный вариант"],["Advance Variation","Вариант выдвижения"],["Accepted","Принятый"],["Declined","Отказанный"],["Modern Variation","Современный вариант"],["Normal Variation","Основной вариант"],["Variation","Вариант"],["Defense","Защита"],["Defence","Защита"],["Opening","Дебют"],["Attack","Атака"],["Gambit","Гамбит"],["System","Система"],["Game","Партия"],["Line","Линия"]],
  zh: [["Classical Variation","古典变例"],["Main Line","主线"],["Exchange Variation","兑换变例"],["Advance Variation","推进变例"],["Accepted","接受型"],["Declined","拒绝型"],["Modern Variation","现代变例"],["Normal Variation","常规变例"],["Variation","变例"],["Defense","防御"],["Defence","防御"],["Opening","开局"],["Attack","进攻"],["Gambit","弃兵"],["System","体系"],["Game","开局"],["Line","路线"]],
  vi: [["Classical Variation","Biến thể Cổ điển"],["Main Line","Biến chính"],["Exchange Variation","Biến đổi quân"],["Advance Variation","Biến tiến tốt"],["Accepted","Chấp nhận"],["Declined","Từ chối"],["Modern Variation","Biến Hiện đại"],["Normal Variation","Biến Thông thường"],["Variation","Biến thể"],["Defense","Phòng thủ"],["Defence","Phòng thủ"],["Opening","Khai cuộc"],["Attack","Tấn công"],["Gambit","Gambit"],["System","Hệ thống"],["Game","Ván cờ"],["Line","Biến"]],
  hi: [["Classical Variation","क्लासिकल वेरिएशन"],["Main Line","मुख्य लाइन"],["Exchange Variation","एक्सचेंज वेरिएशन"],["Advance Variation","एडवांस वेरिएशन"],["Accepted","एक्सेप्टेड"],["Declined","डिक्लाइंड"],["Modern Variation","मॉडर्न वेरिएशन"],["Normal Variation","नॉर्मल वेरिएशन"],["Variation","वेरिएशन"],["Defense","डिफेंस"],["Defence","डिफेंस"],["Opening","ओपनिंग"],["Attack","अटैक"],["Gambit","गैम्बिट"],["System","सिस्टम"],["Game","गेम"],["Line","लाइन"]],
  mr: [["Classical Variation","क्लासिकल व्हेरिएशन"],["Main Line","मुख्य लाईन"],["Exchange Variation","एक्स्चेंज व्हेरिएशन"],["Advance Variation","अॅडव्हान्स व्हेरिएशन"],["Accepted","अॅक्सेप्टेड"],["Declined","डिक्लाइंड"],["Modern Variation","मॉडर्न व्हेरिएशन"],["Normal Variation","नॉर्मल व्हेरिएशन"],["Variation","व्हेरिएशन"],["Defense","डिफेन्स"],["Defence","डिफेन्स"],["Opening","ओपनिंग"],["Attack","अटॅक"],["Gambit","गॅम्बिट"],["System","सिस्टीम"],["Game","गेम"],["Line","लाईन"]],
  pl: [["Classical Variation","Wariant klasyczny"],["Main Line","Główny wariant"],["Exchange Variation","Wariant wymienny"],["Advance Variation","Wariant wysunięcia"],["Accepted","Przyjęty"],["Declined","Nieprzyjęty"],["Modern Variation","Wariant nowoczesny"],["Normal Variation","Wariant główny"],["Variation","Wariant"],["Defense","Obrona"],["Defence","Obrona"],["Opening","Otwarcie"],["Attack","Atak"],["Gambit","Gambit"],["System","System"],["Game","Partia"],["Line","Wariant"]]
};

export function repertoireLanguage(language?: string): Lang {
  const base = (language || "en").split("-")[0].toLowerCase() as Lang;
  return (SUPPORTED as readonly string[]).includes(base) ? base : "en";
}

export function localizeOpeningName(value: string, language?: string) {
  const lang = repertoireLanguage(language);
  if (lang === "en" || !value) return value;
  const [head, ...tail] = value.split(":");
  let result = FAMILIES[lang][head.trim()] || head.trim();
  if (tail.length) result += `: ${tail.join(":").trim()}`;
  for (const [from, to] of PHRASES[lang]) result = result.replace(new RegExp(`\\b${from.replace(/[.*+?^${}()|[\\]\\\\]/g,"\\$&")}\\b`, "g"), to);
  result = applyOpeningSupplement(result, lang);
  return FAMILIES[lang][result] || result;
}

export function localizeMaybeOpening(value: string, language?: string) {
  const lang = repertoireLanguage(language);
  return FAMILIES[lang][value] || localizeOpeningName(value, language);
}
