export type OpeningLang="en"|"es"|"fr"|"de"|"pt"|"ru"|"zh"|"vi"|"hi"|"mr"|"pl";
type Pair=[string,string];
const X:Record<OpeningLang,Pair[]>={
en:[],
es:[["Countergambit","Contragambito"],["Counterattack","Contraataque"],["Delayed","Diferida"],["Symmetrical","Simétrica"],["Two Knights","Dos caballos"],["Three Knights","Tres caballos"],["Four Knights","Cuatro caballos"],["Knight","Caballo"],["Bishop","Alfil"],["Pawn","Peón"],["Trap","Trampa"],["Accelerated","Acelerada"]],
fr:[["Countergambit","Contre-gambit"],["Counterattack","Contre-attaque"],["Delayed","Différée"],["Symmetrical","Symétrique"],["Two Knights","Deux cavaliers"],["Three Knights","Trois cavaliers"],["Four Knights","Quatre cavaliers"],["Knight","Cavalier"],["Bishop","Fou"],["Pawn","Pion"],["Trap","Piège"],["Accelerated","Accélérée"]],
de:[["Countergambit","Gegengambit"],["Counterattack","Gegenangriff"],["Delayed","Verzögert"],["Symmetrical","Symmetrisch"],["Two Knights","Zweispringer"],["Three Knights","Dreispringer"],["Four Knights","Vierspringer"],["Knight","Springer"],["Bishop","Läufer"],["Pawn","Bauer"],["Trap","Falle"],["Accelerated","Beschleunigt"]],
pt:[["Countergambit","Contragambito"],["Counterattack","Contra-ataque"],["Delayed","Adiada"],["Symmetrical","Simétrica"],["Two Knights","Dois cavalos"],["Three Knights","Três cavalos"],["Four Knights","Quatro cavalos"],["Knight","Cavalo"],["Bishop","Bispo"],["Pawn","Peão"],["Trap","Armadilha"],["Accelerated","Acelerada"]],
ru:[["Countergambit","Контргамбит"],["Counterattack","Контратака"],["Delayed","Отложенный"],["Symmetrical","Симметричный"],["Two Knights","Двух коней"],["Three Knights","Трёх коней"],["Four Knights","Четырёх коней"],["Knight","Конь"],["Bishop","Слон"],["Pawn","Пешка"],["Trap","Ловушка"],["Accelerated","Ускоренный"]],
zh:[["Countergambit","反弃兵"],["Counterattack","反击"],["Delayed","延迟"],["Symmetrical","对称"],["Two Knights","双马"],["Three Knights","三马"],["Four Knights","四马"],["Knight","马"],["Bishop","象"],["Pawn","兵"],["Trap","陷阱"],["Accelerated","加速"]],
vi:[["Countergambit","Phản gambit"],["Counterattack","Phản công"],["Delayed","Trì hoãn"],["Symmetrical","Đối xứng"],["Two Knights","Hai Mã"],["Three Knights","Ba Mã"],["Four Knights","Bốn Mã"],["Knight","Mã"],["Bishop","Tượng"],["Pawn","Tốt"],["Trap","Bẫy"],["Accelerated","Tăng tốc"]],
hi:[["Countergambit","प्रतिगैम्बिट"],["Counterattack","प्रत्याक्रमण"],["Delayed","विलंबित"],["Symmetrical","सममित"],["Two Knights","दो घोड़े"],["Three Knights","तीन घोड़े"],["Four Knights","चार घोड़े"],["Knight","घोड़ा"],["Bishop","ऊँट"],["Pawn","प्यादा"],["Trap","जाल"],["Accelerated","त्वरित"]],
mr:[["Countergambit","प्रतिगँबिट"],["Counterattack","प्रतिहल्ला"],["Delayed","विलंबित"],["Symmetrical","सममित"],["Two Knights","दोन घोडे"],["Three Knights","तीन घोडे"],["Four Knights","चार घोडे"],["Knight","घोडा"],["Bishop","उंट"],["Pawn","प्यादा"],["Trap","सापळा"],["Accelerated","वेगवान"]],
pl:[["Countergambit","Kontrgambit"],["Counterattack","Kontratak"],["Delayed","Opóźniony"],["Symmetrical","Symetryczny"],["Two Knights","Dwóch skoczków"],["Three Knights","Trzech skoczków"],["Four Knights","Czterech skoczków"],["Knight","Skoczek"],["Bishop","Goniec"],["Pawn","Pion"],["Trap","Pułapka"],["Accelerated","Przyspieszony"]]};
export function applyOpeningSupplement(value:string,lang:OpeningLang){if(lang==="en")return value;let out=value;for(const [a,b] of X[lang].sort((p,q)=>q[0].length-p[0].length))out=out.split(a).join(b);return out;}
