import React, { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useTranslation } from "react-i18next";
import { Chess } from "chess.js";

import useSettingsStore from "@/stores/SettingsStore";
import EvaluationBar from "@analysis/components/EvaluationBar";
import { classificationColours, classificationImages, classificationNames } from "@analysis/constants/classifications";
import { Classification } from "shared/constants/Classification";
import PieceColour from "shared/constants/PieceColour";

import { analyseRepertoirePosition, evaluateRepertoireMove, RepertoireEngineResult, RepertoireMoveQuality } from "./repertoireEngine";
import { habitAtFen, positionHabitChangeEvent, readPositionHabits, PositionHabit } from "./playerPositionHabits";
import RepertoirePositionContext from "./RepertoirePositionContext";
import * as styles from "./repertoireEngine.module.css";

type Lang = "en"|"es"|"fr"|"de"|"pt"|"ru"|"zh"|"vi"|"hi"|"mr"|"pl";
type Copy = { title:string; intro:string; analyse:string; analysing:string; best:string; line:string; add:string; added:string; games:string; usually:string; observed:string; noHabit:string; error:string; quality:string; coachBest:string; coachGood:string; coachBad:string };
const C:Record<Lang,Copy>={
 en:{title:"Engine recommendation",intro:"Check the current position with Stockfish 17.",analyse:"Ask Stockfish",analysing:"Analysing…",best:"Best move",line:"Suggested continuation",add:"Add this line",added:"Line added",games:"Your recent games",usually:"Here you usually play",observed:"observed games",noHabit:"No imported-game habit is available for this exact position.",error:"Stockfish could not analyse this position. Try again.",quality:"Estimated quality",coachBest:"Stockfish prefers this move. Focus on the idea and continuation.",coachGood:"Your usual move is close to the engine choice.",coachBad:"Your usual move concedes more than the engine choice."},
 es:{title:"Recomendación del motor",intro:"Consulta la posición actual con Stockfish 17.",analyse:"Consultar Stockfish",analysing:"Analizando…",best:"Mejor jugada",line:"Continuación recomendada",add:"Añadir esta línea",added:"Línea añadida",games:"Tus partidas recientes",usually:"Aquí sueles jugar",observed:"partidas observadas",noHabit:"No hay un hábito importado para esta posición exacta.",error:"Stockfish no ha podido analizar esta posición. Inténtalo de nuevo.",quality:"Calidad estimada",coachBest:"Stockfish prefiere esta jugada. Fíjate en la idea y en la continuación.",coachGood:"Tu jugada habitual está cerca de la elección del motor.",coachBad:"Tu jugada habitual cede más que la elección del motor."},
 fr:{title:"Recommandation du moteur",intro:"Analysez la position actuelle avec Stockfish 17.",analyse:"Consulter Stockfish",analysing:"Analyse…",best:"Meilleur coup",line:"Suite recommandée",add:"Ajouter cette ligne",added:"Ligne ajoutée",games:"Vos parties récentes",usually:"Ici, vous jouez habituellement",observed:"parties observées",noHabit:"Aucune habitude importée n'est disponible pour cette position exacte.",error:"Stockfish n'a pas pu analyser cette position. Réessayez.",quality:"Qualité estimée",coachBest:"Stockfish préfère ce coup. Concentrez-vous sur l'idée et la suite.",coachGood:"Votre coup habituel est proche du choix du moteur.",coachBad:"Votre coup habituel concède davantage que le choix du moteur."},
 de:{title:"Engine-Empfehlung",intro:"Analysiere die aktuelle Stellung mit Stockfish 17.",analyse:"Stockfish fragen",analysing:"Analyse…",best:"Bester Zug",line:"Empfohlene Fortsetzung",add:"Diese Variante hinzufügen",added:"Variante hinzugefügt",games:"Deine letzten Partien",usually:"Hier spielst du meistens",observed:"beobachtete Partien",noHabit:"Für diese genaue Stellung gibt es keine importierte Gewohnheit.",error:"Stockfish konnte diese Stellung nicht analysieren. Versuche es erneut.",quality:"Geschätzte Qualität",coachBest:"Stockfish bevorzugt diesen Zug. Achte auf die Idee und die Fortsetzung.",coachGood:"Dein üblicher Zug liegt nahe an der Engine-Wahl.",coachBad:"Dein üblicher Zug gibt mehr preis als die Engine-Wahl."},
 pt:{title:"Recomendação do motor",intro:"Analise a posição atual com Stockfish 17.",analyse:"Consultar Stockfish",analysing:"Analisando…",best:"Melhor lance",line:"Continuação recomendada",add:"Adicionar esta linha",added:"Linha adicionada",games:"Suas partidas recentes",usually:"Aqui você costuma jogar",observed:"partidas observadas",noHabit:"Não há hábito importado para esta posição exata.",error:"O Stockfish não conseguiu analisar esta posição. Tente novamente.",quality:"Qualidade estimada",coachBest:"O Stockfish prefere este lance. Foque na ideia e na continuação.",coachGood:"Seu lance habitual está perto da escolha do motor.",coachBad:"Seu lance habitual cede mais que a escolha do motor."},
 ru:{title:"Рекомендация движка",intro:"Проверьте позицию с помощью Stockfish 17.",analyse:"Спросить Stockfish",analysing:"Анализ…",best:"Лучший ход",line:"Рекомендуемое продолжение",add:"Добавить вариант",added:"Вариант добавлен",games:"Ваши недавние партии",usually:"В этой позиции вы обычно играете",observed:"наблюдаемых партий",noHabit:"Для этой точной позиции нет данных из импортированных партий.",error:"Stockfish не смог проанализировать позицию. Попробуйте ещё раз.",quality:"Оценка качества",coachBest:"Stockfish предпочитает этот ход. Обратите внимание на идею и продолжение.",coachGood:"Ваш обычный ход близок к выбору движка.",coachBad:"Ваш обычный ход уступает выбору движка."},
 zh:{title:"引擎建议",intro:"使用 Stockfish 17 分析当前局面。",analyse:"询问 Stockfish",analysing:"分析中…",best:"最佳着法",line:"推荐后续",add:"添加此线路",added:"线路已添加",games:"你的近期对局",usually:"你在这里通常会走",observed:"盘已观察对局",noHabit:"该精确局面暂无导入对局习惯数据。",error:"Stockfish 无法分析该局面，请重试。",quality:"估计质量",coachBest:"Stockfish 更推荐这一步。重点理解它的思路和后续。",coachGood:"你的常用着法与引擎选择接近。",coachBad:"你的常用着法比引擎选择损失更多。"},
 vi:{title:"Gợi ý của máy",intro:"Phân tích thế cờ hiện tại với Stockfish 17.",analyse:"Hỏi Stockfish",analysing:"Đang phân tích…",best:"Nước tốt nhất",line:"Biến tiếp diễn đề xuất",add:"Thêm biến này",added:"Đã thêm biến",games:"Các ván gần đây của bạn",usually:"Ở đây bạn thường đi",observed:"ván đã quan sát",noHabit:"Không có dữ liệu thói quen đã nhập cho chính xác thế cờ này.",error:"Stockfish không thể phân tích thế cờ này. Hãy thử lại.",quality:"Chất lượng ước tính",coachBest:"Stockfish ưu tiên nước này. Hãy tập trung vào ý tưởng và biến tiếp diễn.",coachGood:"Nước bạn thường chơi khá gần lựa chọn của máy.",coachBad:"Nước bạn thường chơi mất nhiều hơn lựa chọn của máy."},
 hi:{title:"इंजन की सिफारिश",intro:"Stockfish 17 से मौजूदा स्थिति जाँचें।",analyse:"Stockfish से पूछें",analysing:"विश्लेषण हो रहा है…",best:"सर्वश्रेष्ठ चाल",line:"सुझाई गई अगली चालें",add:"यह लाइन जोड़ें",added:"लाइन जोड़ दी गई",games:"आपकी हाल की बाजियाँ",usually:"यहाँ आप आम तौर पर चलते हैं",observed:"देखी गई बाजियाँ",noHabit:"इस सटीक स्थिति के लिए आयातित बाजियों का डेटा उपलब्ध नहीं है।",error:"Stockfish इस स्थिति का विश्लेषण नहीं कर सका। फिर कोशिश करें।",quality:"अनुमानित गुणवत्ता",coachBest:"Stockfish इस चाल को प्राथमिकता देता है। विचार और आगे की लाइन समझें।",coachGood:"आपकी सामान्य चाल इंजन की पसंद के करीब है।",coachBad:"आपकी सामान्य चाल इंजन की पसंद से अधिक नुकसान देती है।"},
 mr:{title:"इंजिनची शिफारस",intro:"Stockfish 17 ने सध्याची स्थिती तपासा.",analyse:"Stockfish ला विचारा",analysing:"विश्लेषण सुरू आहे…",best:"सर्वोत्तम चाल",line:"सुचवलेली पुढील चाल",add:"ही लाईन जोडा",added:"लाईन जोडली",games:"तुमचे अलीकडील सामने",usually:"इथे तुम्ही सहसा खेळता",observed:"पाहिलेले सामने",noHabit:"या अचूक स्थितीसाठी आयात केलेल्या सामन्यांचा डेटा उपलब्ध नाही.",error:"Stockfish या स्थितीचे विश्लेषण करू शकला नाही. पुन्हा प्रयत्न करा.",quality:"अंदाजे गुणवत्ता",coachBest:"Stockfish ही चाल पसंत करतो. कल्पना आणि पुढील लाईन समजून घ्या.",coachGood:"तुमची नेहमीची चाल इंजिनच्या निवडीजवळ आहे.",coachBad:"तुमची नेहमीची चाल इंजिनच्या निवडीपेक्षा जास्त नुकसान करते."},
 pl:{title:"Rekomendacja silnika",intro:"Sprawdź bieżącą pozycję ze Stockfishem 17.",analyse:"Zapytaj Stockfisha",analysing:"Analiza…",best:"Najlepszy ruch",line:"Zalecana kontynuacja",add:"Dodaj ten wariant",added:"Wariant dodany",games:"Twoje ostatnie partie",usually:"Tutaj zwykle grasz",observed:"zaobserwowanych partii",noHabit:"Dla tej dokładnej pozycji nie ma danych z zaimportowanych partii.",error:"Stockfish nie zdołał przeanalizować pozycji. Spróbuj ponownie.",quality:"Szacowana jakość",coachBest:"Stockfish preferuje ten ruch. Skup się na idei i kontynuacji.",coachGood:"Twój zwykły ruch jest blisko wyboru silnika.",coachBad:"Twój zwykły ruch oddaje więcej niż wybór silnika."}
};
function lang(value:string):Lang{const x=value.split("-")[0].toLowerCase() as Lang;return x in C?x:"en";}
function score(result:RepertoireEngineResult){if(result.evaluation.type=="mate")return `M${Math.abs(result.evaluation.value)}`;return `${result.evaluation.value>=0?"+":""}${(result.evaluation.value/100).toFixed(2)}`;}

interface Props{fen:string;onAddLine?:(pvUci:string[],suggestedName:string)=>void;onRecommendation?:(bestUci?:string)=>void;className?:string;}

function RepertoireEngineInsight({fen,onAddLine,onRecommendation,className}:Props){
 const {t,i18n}=useTranslation();
 const settings=useSettingsStore(s=>s.settings);
 const copy=C[lang(i18n.resolvedLanguage||i18n.language||"en")];
 const [result,setResult]=useState<RepertoireEngineResult>();
 const [quality,setQuality]=useState<RepertoireMoveQuality>();
 const [habit,setHabit]=useState<PositionHabit>();
 const [loading,setLoading]=useState(false);
 const [error,setError]=useState(false);
 const [added,setAdded]=useState(false);
 const [courseHost,setCourseHost]=useState<HTMLElement|null>(null);
 const [courseFlipped,setCourseFlipped]=useState(false);
 const requestRef=useRef(0);
 const habitual=habit?.moves[0];
 const refreshHabit=()=>setHabit(habitAtFen(fen,readPositionHabits()));

 useEffect(()=>{requestRef.current++;setResult(undefined);setQuality(undefined);setError(false);setAdded(false);onRecommendation?.(undefined);refreshHabit();const frame=requestAnimationFrame(()=>setCourseHost(document.getElementById("repertoire-course-board-v3")?.parentElement||null));return()=>cancelAnimationFrame(frame);},[fen]);
 useEffect(()=>{const event=positionHabitChangeEvent();const listener=()=>refreshHabit();window.addEventListener(event,listener);return()=>window.removeEventListener(event,listener);},[fen]);
 useEffect(()=>{if(!courseHost)return;const section=courseHost.closest("section");const update=()=>{const active=section?.querySelector("header button[data-active=\"true\"]") as HTMLElement|null;const parent=active?.parentElement;setCourseFlipped(Boolean(parent&&active&&Array.from(parent.children).indexOf(active)==1));};update();const observer=new MutationObserver(update);if(section)observer.observe(section,{attributes:true,subtree:true,attributeFilter:["data-active"]});return()=>observer.disconnect();},[courseHost]);

 async function analyse(){if(!settings.analysis.engine.enabled)return;const request=++requestRef.current;setLoading(true);setError(false);setQuality(undefined);setAdded(false);try{const next=await analyseRepertoirePosition(fen);if(request!=requestRef.current)return;setResult(next);onRecommendation?.(next.bestUci);if(habitual){try{const q=await evaluateRepertoireMove(fen,habitual.uci,next);if(request==requestRef.current)setQuality(q);}catch{if(request==requestRef.current)setQuality(undefined);}}}catch{if(request!=requestRef.current)return;setError(true);setResult(undefined);onRecommendation?.(undefined);}finally{if(request==requestRef.current)setLoading(false);}}
 useEffect(()=>{if(!settings.analysis.engine.enabled||!courseHost)return;const timer=window.setTimeout(()=>void analyse(),300);return()=>window.clearTimeout(timer);},[fen,courseHost,settings.analysis.engine.enabled]);

 const coachText=useMemo(()=>{if(!result)return"";const pv=result.pvSan.slice(0,5).join(" ");if(!quality||!habitual)return `${copy.coachBest} ${copy.best}: ${result.bestSan}. ${copy.line}: ${pv}.`;const good=[Classification.BEST,Classification.EXCELLENT,Classification.OKAY].includes(quality.classification);return `${good?copy.coachGood:copy.coachBad} ${copy.usually} ${habitual.san}; ${copy.best}: ${result.bestSan}. ${copy.line}: ${pv}.`;},[result,quality,habitual,copy]);
 if(!settings.analysis.engine.enabled)return null;
 const turn=new Chess(fen).turn();
 const moveColour=turn=="w"?PieceColour.WHITE:PieceColour.BLACK;
 const evaluation=result?.evaluation||{type:"centipawn" as const,value:0};
 const bar=courseHost?createPortal(<EvaluationBar className={styles.courseEvaluationBar} evaluation={evaluation} moveColour={moveColour} flipped={courseFlipped}/>,courseHost):null;

 return <>{bar}<section className={`${styles.engineCard} ${className||""}`} data-repertoire-tour="stockfish"><div className={styles.engineHeader}><div><span>STOCKFISH 17</span><strong>{copy.title}</strong></div>{result&&<b>{score(result)}</b>}</div><RepertoirePositionContext fen={fen} onAddLine={onAddLine} onAskStockfish={()=>void analyse()}/>{!result&&!loading&&<><p>{copy.intro}</p><button type="button" className={styles.primary} onClick={analyse}>{copy.analyse}</button></>}{loading&&<div className={styles.loading}><i/><span>{copy.analysing}</span></div>}{error&&<><p className={styles.error}>{copy.error}</p><button type="button" className={styles.primary} onClick={analyse}>{copy.analyse}</button></>}{result&&!loading&&<><div className={styles.bestMove}><span>{copy.best}</span><strong>{result.bestSan}</strong></div><div className={styles.pv}><span>{copy.line}</span><p>{result.pvSan.join(" ")}</p></div>{onAddLine&&<button type="button" className={styles.primary} disabled={added} onClick={()=>{onAddLine(result.pvUci,`Stockfish · ${result.bestSan}`);setAdded(true);}}>{added?copy.added:copy.add}</button>}{habitual&&quality&&<div className={styles.habitBlock}><span>{copy.quality}</span><div className={styles.quality} style={{color:classificationColours[quality.classification]}}><img src={classificationImages[quality.classification]} alt=""/><strong>{t(classificationNames[quality.classification])}</strong><small>{copy.quality}{quality.lossCp>0?` · −${quality.lossCp} cp`:""}</small></div></div>}{settings.coach.enabled&&<div className={styles.coachComment}><span>♟</span><p>{coachText}</p></div>}</>}</section></>;
}
export default RepertoireEngineInsight;