export const ADSENSE_PUBLISHER_ID = "7938339532578559";
export const ADSENSE_ACCOUNT_ID = `ca-pub-${ADSENSE_PUBLISHER_ID}`;
export const ADSENSE_ADS_TXT_PUBLISHER_ID = `pub-${ADSENSE_PUBLISHER_ID}`;
export const ADSENSE_ADS_TXT_CONTENT = `google.com, ${ADSENSE_ADS_TXT_PUBLISHER_ID}, DIRECT, f08c47fec0942fa0\n`;
