import type { LegalDocumentCopy, LegalSection } from "../../components/LegalDocument";

type AnalyticsPrivacyPatch = {
    updated: string;
    plainSummary: string;
    dataBullet: string;
    purposeBullet: string;
    browserStorageParagraph: string;
    providerBullet: string;
    retentionParagraph: string;
};

const patches: Record<string, AnalyticsPrivacyPatch> = {
    en: {
        updated: "Last updated: 7 August 2026",
        plainSummary: "Analysis can remain in your browser. An optional account adds necessary authentication cookies and cloud storage. If you consent to Analytics, NexoChess also uses Google Analytics 4 to understand aggregate website usage. Advertising remains disabled.",
        dataBullet: "Optional analytics data after consent: page URL and title, session and usage statistics, approximate geography, browser and device information, and pseudonymous client/session identifiers generated by Google Analytics 4. NexoChess does not intentionally send chess-game content or NexoChess account identifiers to GA4.",
        purposeBullet: "Measure aggregate website use and improve NexoChess through Google Analytics 4 only after Analytics consent. Advertising measurement and personalisation remain disabled at this stage.",
        browserStorageParagraph: "When you sign in, strictly necessary authentication cookies or equivalent session storage keep the session secure. If you grant Analytics consent, Google Analytics 4 may set first-party cookies such as _ga and _ga_<container-id> to distinguish pseudonymous users and maintain session state; Google documents a default lifetime of up to two years, subject to browser limits. The Google Analytics tag is not loaded before Analytics consent. If you later withdraw that consent, NexoChess updates analytics consent to denied; existing analytics cookies may remain until you delete them or they expire. Clearing authentication cookies may sign you out.",
        providerBullet: "Google Analytics 4 (Google): optional, consent-based measurement of website usage. Advertising storage, advertising user data, advertising personalisation and Google Signals are disabled by the NexoChess integration at this stage.",
        retentionParagraph: "Google Analytics data is retained according to the retention settings of the NexoChess GA4 property and Google's applicable controls. GA4 first-party cookies have Google-documented default lifetimes of up to two years, although browser policies may shorten them. You can withdraw Analytics consent at any time through NexoChess data-consent settings."
    },
    es: {
        updated: "Última actualización: 7 de agosto de 2026",
        plainSummary: "El análisis puede permanecer en tu navegador. Una cuenta opcional añade cookies necesarias de autenticación y almacenamiento en la nube. Si consientes la Analítica, NexoChess también utiliza Google Analytics 4 para conocer de forma agregada el uso de la web. La publicidad sigue desactivada.",
        dataBullet: "Datos opcionales de analítica tras el consentimiento: URL y título de la página, estadísticas de sesión y uso, ubicación geográfica aproximada, información del navegador y dispositivo e identificadores seudónimos de cliente y sesión generados por Google Analytics 4. NexoChess no envía intencionadamente a GA4 el contenido de las partidas de ajedrez ni identificadores de cuenta de NexoChess.",
        purposeBullet: "Medir de forma agregada el uso de la web y mejorar NexoChess mediante Google Analytics 4 únicamente después del consentimiento de Analítica. La medición publicitaria y la personalización publicitaria permanecen desactivadas en esta fase.",
        browserStorageParagraph: "Al iniciar sesión, las cookies de autenticación estrictamente necesarias o el almacenamiento de sesión equivalente mantienen la sesión segura. Si autorizas Analítica, Google Analytics 4 puede establecer cookies propias como _ga y _ga_<container-id> para distinguir usuarios seudónimos y mantener el estado de la sesión; Google indica una duración predeterminada de hasta dos años, sujeta a los límites del navegador. La etiqueta de Google Analytics no se carga antes del consentimiento de Analítica. Si después retiras ese consentimiento, NexoChess actualiza el consentimiento de analítica a denegado; las cookies analíticas existentes pueden permanecer hasta que las elimines o caduquen. Borrar las cookies de autenticación puede cerrar tu sesión.",
        providerBullet: "Google Analytics 4 (Google): medición opcional y basada en consentimiento del uso de la web. El almacenamiento publicitario, los datos de usuario para publicidad, la personalización publicitaria y Google Signals están desactivados por la integración de NexoChess en esta fase.",
        retentionParagraph: "Los datos de Google Analytics se conservan según la configuración de retención de la propiedad GA4 de NexoChess y los controles aplicables de Google. Las cookies propias de GA4 tienen una duración predeterminada documentada por Google de hasta dos años, aunque las políticas del navegador pueden acortarla. Puedes retirar el consentimiento de Analítica en cualquier momento desde los ajustes de consentimiento de datos de NexoChess."
    },
    fr: {
        updated: "Dernière mise à jour : 7 août 2026",
        plainSummary: "L’analyse peut rester dans votre navigateur. Un compte facultatif ajoute les cookies d’authentification nécessaires et le stockage dans le cloud. Si vous consentez aux statistiques, NexoChess utilise également Google Analytics 4 pour comprendre l’utilisation agrégée du site. La publicité reste désactivée.",
        dataBullet: "Données statistiques facultatives après consentement : URL et titre de la page, statistiques de session et d’utilisation, localisation approximative, informations sur le navigateur et l’appareil, ainsi que des identifiants pseudonymes de client et de session générés par Google Analytics 4. NexoChess n’envoie pas intentionnellement à GA4 le contenu des parties d’échecs ni les identifiants de compte NexoChess.",
        purposeBullet: "Mesurer l’utilisation agrégée du site et améliorer NexoChess avec Google Analytics 4 uniquement après consentement aux statistiques. La mesure publicitaire et la personnalisation publicitaire restent désactivées à ce stade.",
        browserStorageParagraph: "Lorsque vous vous connectez, des cookies d’authentification strictement nécessaires ou un stockage de session équivalent sécurisent la session. Si vous autorisez les statistiques, Google Analytics 4 peut définir des cookies propriétaires tels que _ga et _ga_<container-id> afin de distinguer des utilisateurs pseudonymes et de conserver l’état de session ; Google indique une durée par défaut pouvant aller jusqu’à deux ans, sous réserve des limites du navigateur. La balise Google Analytics n’est pas chargée avant votre consentement. Si vous retirez ensuite ce consentement, NexoChess met le consentement analytique à refusé ; les cookies existants peuvent rester jusqu’à leur suppression ou expiration. La suppression des cookies d’authentification peut vous déconnecter.",
        providerBullet: "Google Analytics 4 (Google) : mesure facultative de l’utilisation du site fondée sur le consentement. Le stockage publicitaire, les données utilisateur publicitaires, la personnalisation publicitaire et Google Signals sont désactivés par l’intégration NexoChess à ce stade.",
        retentionParagraph: "Les données Google Analytics sont conservées selon les paramètres de conservation de la propriété GA4 de NexoChess et les contrôles applicables de Google. Les cookies propriétaires GA4 ont une durée par défaut documentée par Google pouvant aller jusqu’à deux ans, bien que les règles du navigateur puissent la réduire. Vous pouvez retirer votre consentement aux statistiques à tout moment dans les paramètres de consentement de NexoChess."
    },
    de: {
        updated: "Zuletzt aktualisiert: 7. August 2026",
        plainSummary: "Die Analyse kann in Ihrem Browser verbleiben. Ein optionales Konto fügt notwendige Authentifizierungs-Cookies und Cloud-Speicherung hinzu. Wenn Sie Analyse zustimmen, verwendet NexoChess außerdem Google Analytics 4, um die aggregierte Websitenutzung zu verstehen. Werbung bleibt deaktiviert.",
        dataBullet: "Optionale Analysedaten nach Einwilligung: Seiten-URL und -Titel, Sitzungs- und Nutzungsstatistiken, ungefährer geografischer Standort, Browser- und Geräteinformationen sowie von Google Analytics 4 erzeugte pseudonyme Client- und Sitzungskennungen. NexoChess übermittelt nicht absichtlich Inhalte von Schachpartien oder NexoChess-Kontokennungen an GA4.",
        purposeBullet: "Aggregierte Websitenutzung messen und NexoChess mithilfe von Google Analytics 4 verbessern, jedoch nur nach Einwilligung in Analyse. Werbemessung und personalisierte Werbung bleiben in dieser Phase deaktiviert.",
        browserStorageParagraph: "Wenn Sie sich anmelden, sichern unbedingt erforderliche Authentifizierungs-Cookies oder gleichwertiger Sitzungsspeicher die Sitzung. Wenn Sie Analyse erlauben, kann Google Analytics 4 Erstanbieter-Cookies wie _ga und _ga_<container-id> setzen, um pseudonyme Nutzer zu unterscheiden und den Sitzungsstatus zu erhalten; Google dokumentiert eine Standardlaufzeit von bis zu zwei Jahren, vorbehaltlich Browserbeschränkungen. Das Google-Analytics-Tag wird vor der Einwilligung nicht geladen. Widerrufen Sie die Einwilligung später, setzt NexoChess die Analyse-Einwilligung auf verweigert; vorhandene Analyse-Cookies können bis zur Löschung oder ihrem Ablauf bestehen bleiben. Das Löschen von Authentifizierungs-Cookies kann Sie abmelden.",
        providerBullet: "Google Analytics 4 (Google): optionale, einwilligungsbasierte Messung der Websitenutzung. Werbespeicherung, Werbenutzerdaten, personalisierte Werbung und Google Signals sind durch die NexoChess-Integration in dieser Phase deaktiviert.",
        retentionParagraph: "Google-Analytics-Daten werden gemäß den Aufbewahrungseinstellungen der NexoChess-GA4-Property und den anwendbaren Google-Kontrollen gespeichert. GA4-Erstanbieter-Cookies haben laut Google standardmäßig eine Laufzeit von bis zu zwei Jahren, wobei Browserregeln diese verkürzen können. Sie können Ihre Analyse-Einwilligung jederzeit in den NexoChess-Datenschutzeinstellungen widerrufen."
    },
    pt: {
        updated: "Última atualização: 7 de agosto de 2026",
        plainSummary: "A análise pode permanecer no seu navegador. Uma conta opcional acrescenta cookies de autenticação necessários e armazenamento na nuvem. Se consentir com a Analítica, o NexoChess também utiliza o Google Analytics 4 para compreender a utilização agregada do site. A publicidade continua desativada.",
        dataBullet: "Dados opcionais de analítica após consentimento: URL e título da página, estatísticas de sessão e utilização, localização geográfica aproximada, informações do navegador e dispositivo e identificadores pseudónimos de cliente e sessão gerados pelo Google Analytics 4. O NexoChess não envia intencionalmente para o GA4 o conteúdo das partidas de xadrez nem identificadores de conta do NexoChess.",
        purposeBullet: "Medir de forma agregada a utilização do site e melhorar o NexoChess com o Google Analytics 4 apenas após consentimento para Analítica. A medição e a personalização publicitárias permanecem desativadas nesta fase.",
        browserStorageParagraph: "Ao iniciar sessão, cookies de autenticação estritamente necessários ou armazenamento de sessão equivalente mantêm a sessão segura. Se autorizar Analítica, o Google Analytics 4 pode definir cookies próprios como _ga e _ga_<container-id> para distinguir utilizadores pseudónimos e manter o estado da sessão; a Google documenta uma duração predefinida de até dois anos, sujeita aos limites do navegador. A etiqueta do Google Analytics não é carregada antes do consentimento. Se posteriormente retirar o consentimento, o NexoChess atualiza o consentimento de analítica para negado; cookies analíticos existentes podem permanecer até serem apagados ou expirarem. Apagar cookies de autenticação pode terminar a sessão.",
        providerBullet: "Google Analytics 4 (Google): medição opcional e baseada em consentimento da utilização do site. O armazenamento publicitário, os dados de utilizador para publicidade, a personalização publicitária e o Google Signals estão desativados pela integração do NexoChess nesta fase.",
        retentionParagraph: "Os dados do Google Analytics são conservados de acordo com as definições de retenção da propriedade GA4 do NexoChess e os controlos aplicáveis da Google. Os cookies próprios do GA4 têm uma duração predefinida documentada de até dois anos, embora as políticas do navegador possam reduzi-la. Pode retirar o consentimento para Analítica a qualquer momento nas definições de consentimento de dados do NexoChess."
    },
    ru: {
        updated: "Последнее обновление: 7 августа 2026 г.",
        plainSummary: "Анализ может оставаться в вашем браузере. Необязательная учётная запись добавляет необходимые cookies аутентификации и облачное хранение. Если вы согласитесь на аналитику, NexoChess также использует Google Analytics 4 для понимания агрегированного использования сайта. Реклама остаётся отключённой.",
        dataBullet: "Необязательные аналитические данные после согласия: URL и заголовок страницы, статистика сеансов и использования, приблизительное местоположение, сведения о браузере и устройстве, а также псевдонимные идентификаторы клиента и сеанса, создаваемые Google Analytics 4. NexoChess намеренно не передаёт в GA4 содержимое шахматных партий или идентификаторы учётной записи NexoChess.",
        purposeBullet: "Измерять агрегированное использование сайта и улучшать NexoChess с помощью Google Analytics 4 только после согласия на аналитику. Измерение рекламы и персонализация рекламы на этом этапе остаются отключёнными.",
        browserStorageParagraph: "При входе строго необходимые cookies аутентификации или эквивалентное хранилище сеанса обеспечивают безопасность сеанса. Если вы разрешите аналитику, Google Analytics 4 может установить собственные cookies, например _ga и _ga_<container-id>, чтобы различать псевдонимных пользователей и сохранять состояние сеанса; Google указывает срок по умолчанию до двух лет с учётом ограничений браузера. Тег Google Analytics не загружается до согласия. Если затем отозвать согласие, NexoChess меняет состояние согласия на аналитику на отказ; существующие аналитические cookies могут сохраняться до удаления или истечения срока. Удаление cookies аутентификации может привести к выходу из аккаунта.",
        providerBullet: "Google Analytics 4 (Google): необязательное измерение использования сайта на основании согласия. Рекламное хранилище, рекламные пользовательские данные, персонализация рекламы и Google Signals на этом этапе отключены интеграцией NexoChess.",
        retentionParagraph: "Данные Google Analytics хранятся в соответствии с настройками хранения ресурса GA4 NexoChess и применимыми средствами управления Google. Для собственных cookies GA4 Google указывает срок по умолчанию до двух лет, хотя правила браузера могут его сократить. Вы можете в любое время отозвать согласие на аналитику в настройках согласия NexoChess."
    },
    zh: {
        updated: "最后更新：2026年8月7日",
        plainSummary: "分析可以保留在你的浏览器中。可选账户会增加必要的身份验证 Cookie 和云端存储。如果你同意“分析”，NexoChess 还会使用 Google Analytics 4 了解网站的汇总使用情况。广告功能仍保持关闭。",
        dataBullet: "同意后可选收集的分析数据：页面 URL 和标题、会话与使用统计、粗略地理位置、浏览器和设备信息，以及 Google Analytics 4 生成的匿名化客户端/会话标识符。NexoChess 不会有意向 GA4 发送棋局内容或 NexoChess 账户标识符。",
        purposeBullet: "仅在获得“分析”同意后，通过 Google Analytics 4 衡量网站的汇总使用情况并改进 NexoChess。本阶段广告衡量和广告个性化仍处于关闭状态。",
        browserStorageParagraph: "登录时，严格必要的身份验证 Cookie 或等效会话存储用于保障会话安全。如果你允许“分析”，Google Analytics 4 可能会设置第一方 Cookie（例如 _ga 和 _ga_<container-id>），用于区分匿名化用户并维持会话状态；Google 记录的默认期限最长为两年，但会受浏览器限制影响。在获得“分析”同意前不会加载 Google Analytics 标签。若你之后撤回同意，NexoChess 会把分析存储权限更新为拒绝；已有分析 Cookie 可能会保留到你删除它们或其到期。删除身份验证 Cookie 可能会使你退出登录。",
        providerBullet: "Google Analytics 4（Google）：基于同意的可选网站使用情况衡量。本阶段 NexoChess 集成会关闭广告存储、广告用户数据、广告个性化和 Google Signals。",
        retentionParagraph: "Google Analytics 数据会按照 NexoChess GA4 媒体资源的保留设置和 Google 的适用控制项保存。Google 记录的 GA4 第一方 Cookie 默认期限最长为两年，但浏览器政策可能会缩短期限。你可以随时在 NexoChess 的数据同意设置中撤回“分析”同意。"
    },
    vi: {
        updated: "Cập nhật lần cuối: 7 tháng 8 năm 2026",
        plainSummary: "Phân tích có thể vẫn nằm trong trình duyệt của bạn. Tài khoản tùy chọn bổ sung cookie xác thực cần thiết và lưu trữ đám mây. Nếu bạn đồng ý với Phân tích, NexoChess cũng sử dụng Google Analytics 4 để hiểu mức sử dụng trang web ở dạng tổng hợp. Quảng cáo vẫn bị tắt.",
        dataBullet: "Dữ liệu phân tích tùy chọn sau khi đồng ý: URL và tiêu đề trang, số liệu phiên và mức sử dụng, vị trí địa lý gần đúng, thông tin trình duyệt và thiết bị, cùng các mã nhận dạng khách hàng/phiên dạng giả danh do Google Analytics 4 tạo. NexoChess không chủ ý gửi nội dung ván cờ hoặc mã nhận dạng tài khoản NexoChess tới GA4.",
        purposeBullet: "Đo lường mức sử dụng trang web ở dạng tổng hợp và cải thiện NexoChess bằng Google Analytics 4 chỉ sau khi có sự đồng ý với Phân tích. Đo lường quảng cáo và cá nhân hóa quảng cáo vẫn bị tắt ở giai đoạn này.",
        browserStorageParagraph: "Khi bạn đăng nhập, cookie xác thực thực sự cần thiết hoặc bộ nhớ phiên tương đương giúp bảo mật phiên. Nếu bạn cho phép Phân tích, Google Analytics 4 có thể đặt cookie của bên thứ nhất như _ga và _ga_<container-id> để phân biệt người dùng giả danh và duy trì trạng thái phiên; Google công bố thời hạn mặc định tối đa hai năm, tùy theo giới hạn của trình duyệt. Thẻ Google Analytics không được tải trước khi có sự đồng ý. Nếu sau đó bạn rút lại sự đồng ý, NexoChess cập nhật quyền lưu trữ phân tích thành bị từ chối; cookie phân tích hiện có có thể vẫn còn cho đến khi bạn xóa hoặc chúng hết hạn. Xóa cookie xác thực có thể đăng xuất bạn.",
        providerBullet: "Google Analytics 4 (Google): đo lường mức sử dụng trang web tùy chọn dựa trên sự đồng ý. Lưu trữ quảng cáo, dữ liệu người dùng quảng cáo, cá nhân hóa quảng cáo và Google Signals đều bị tích hợp NexoChess tắt ở giai đoạn này.",
        retentionParagraph: "Dữ liệu Google Analytics được lưu theo cài đặt lưu giữ của thuộc tính GA4 NexoChess và các tùy chọn kiểm soát hiện hành của Google. Cookie bên thứ nhất của GA4 có thời hạn mặc định do Google công bố lên đến hai năm, dù chính sách trình duyệt có thể rút ngắn thời gian này. Bạn có thể rút lại sự đồng ý với Phân tích bất cứ lúc nào trong cài đặt đồng ý dữ liệu của NexoChess."
    },
    hi: {
        updated: "अंतिम अपडेट: 7 अगस्त 2026",
        plainSummary: "विश्लेषण आपके ब्राउज़र में रह सकता है। वैकल्पिक खाता आवश्यक प्रमाणीकरण कुकी और क्लाउड स्टोरेज जोड़ता है। यदि आप Analytics के लिए सहमति देते हैं, तो NexoChess वेबसाइट के समेकित उपयोग को समझने के लिए Google Analytics 4 का भी उपयोग करता है। विज्ञापन अभी बंद है।",
        dataBullet: "सहमति के बाद वैकल्पिक Analytics डेटा: पेज URL और शीर्षक, सत्र और उपयोग आँकड़े, अनुमानित भौगोलिक स्थान, ब्राउज़र और डिवाइस की जानकारी, तथा Google Analytics 4 द्वारा बनाए गए छद्मनामित क्लाइंट/सत्र पहचानकर्ता। NexoChess जानबूझकर शतरंज की बाज़ियों की सामग्री या NexoChess खाता पहचानकर्ता GA4 को नहीं भेजता।",
        purposeBullet: "केवल Analytics सहमति के बाद Google Analytics 4 से वेबसाइट के समेकित उपयोग को मापना और NexoChess को बेहतर बनाना। इस चरण में विज्ञापन मापन और विज्ञापन वैयक्तिकरण बंद रहते हैं।",
        browserStorageParagraph: "साइन इन करने पर सख्ती से आवश्यक प्रमाणीकरण कुकी या समान सत्र स्टोरेज सत्र को सुरक्षित रखते हैं। यदि आप Analytics की अनुमति देते हैं, तो Google Analytics 4 छद्मनामित उपयोगकर्ताओं को अलग पहचानने और सत्र की स्थिति बनाए रखने के लिए _ga और _ga_<container-id> जैसी प्रथम-पक्ष कुकी सेट कर सकता है; Google इनके लिए डिफ़ॉल्ट अवधि अधिकतम दो वर्ष बताता है, जो ब्राउज़र सीमाओं के अधीन है। Analytics सहमति से पहले Google Analytics टैग लोड नहीं होता। यदि आप बाद में सहमति वापस लेते हैं, तो NexoChess Analytics सहमति को denied पर अपडेट करता है; मौजूदा Analytics कुकी आपके हटाने या उनके समाप्त होने तक रह सकती हैं। प्रमाणीकरण कुकी हटाने पर आप साइन आउट हो सकते हैं।",
        providerBullet: "Google Analytics 4 (Google): सहमति-आधारित वैकल्पिक वेबसाइट उपयोग मापन। इस चरण में NexoChess एकीकरण विज्ञापन स्टोरेज, विज्ञापन उपयोगकर्ता डेटा, विज्ञापन वैयक्तिकरण और Google Signals को बंद रखता है।",
        retentionParagraph: "Google Analytics डेटा NexoChess की GA4 प्रॉपर्टी की डेटा-रिटेंशन सेटिंग और Google के लागू नियंत्रणों के अनुसार रखा जाता है। GA4 प्रथम-पक्ष कुकी की Google-दस्तावेज़ित डिफ़ॉल्ट अवधि अधिकतम दो वर्ष है, हालांकि ब्राउज़र नीतियाँ इसे कम कर सकती हैं। आप NexoChess की डेटा-सहमति सेटिंग से किसी भी समय Analytics सहमति वापस ले सकते हैं।"
    },
    mr: {
        updated: "शेवटचे अद्यतन: 7 ऑगस्ट 2026",
        plainSummary: "विश्लेषण तुमच्या ब्राउझरमध्येच राहू शकते. ऐच्छिक खाते आवश्यक प्रमाणीकरण कुकीज आणि क्लाउड स्टोरेज जोडते. तुम्ही Analytics ला संमती दिल्यास, NexoChess वेबसाइटचा एकत्रित वापर समजण्यासाठी Google Analytics 4 देखील वापरते. जाहिरात अद्याप बंद आहे.",
        dataBullet: "संमतीनंतरचे ऐच्छिक Analytics डेटा: पृष्ठ URL व शीर्षक, सत्र व वापर आकडेवारी, अंदाजे भौगोलिक स्थान, ब्राउझर व डिव्हाइस माहिती आणि Google Analytics 4 ने तयार केलेले छद्मनामी क्लायंट/सत्र ओळखचिन्ह. NexoChess जाणीवपूर्वक बुद्धिबळ सामन्यांची सामग्री किंवा NexoChess खाते ओळखचिन्ह GA4 कडे पाठवत नाही.",
        purposeBullet: "फक्त Analytics संमतीनंतर Google Analytics 4 द्वारे वेबसाइटचा एकत्रित वापर मोजणे आणि NexoChess सुधारणे. या टप्प्यावर जाहिरात मापन आणि जाहिरात वैयक्तिकीकरण बंद राहते.",
        browserStorageParagraph: "साइन इन केल्यावर काटेकोरपणे आवश्यक प्रमाणीकरण कुकीज किंवा समतुल्य सत्र स्टोरेज सत्र सुरक्षित ठेवते. तुम्ही Analytics ला परवानगी दिल्यास, Google Analytics 4 छद्मनामी वापरकर्ते वेगळे ओळखण्यासाठी आणि सत्र स्थिती राखण्यासाठी _ga व _ga_<container-id> सारख्या प्रथम-पक्ष कुकीज सेट करू शकते; Google त्यांचा डीफॉल्ट कालावधी कमाल दोन वर्षे सांगते, जो ब्राउझर मर्यादांच्या अधीन आहे. Analytics संमतीपूर्वी Google Analytics टॅग लोड होत नाही. नंतर संमती मागे घेतल्यास NexoChess Analytics संमती denied वर अद्यतनित करते; विद्यमान Analytics कुकीज तुम्ही हटवेपर्यंत किंवा त्या कालबाह्य होईपर्यंत राहू शकतात. प्रमाणीकरण कुकीज हटवल्यास तुम्ही साइन आउट होऊ शकता.",
        providerBullet: "Google Analytics 4 (Google): संमतीवर आधारित ऐच्छिक वेबसाइट वापर मापन. या टप्प्यावर NexoChess एकत्रीकरण जाहिरात स्टोरेज, जाहिरात वापरकर्ता डेटा, जाहिरात वैयक्तिकीकरण आणि Google Signals बंद ठेवते.",
        retentionParagraph: "Google Analytics डेटा NexoChess GA4 प्रॉपर्टीच्या डेटा-रिटेंशन सेटिंग्ज आणि Google च्या लागू नियंत्रणांनुसार ठेवला जातो. GA4 प्रथम-पक्ष कुकीजचा Google-दस्तऐवजीकृत डीफॉल्ट कालावधी कमाल दोन वर्षे आहे, जरी ब्राउझर धोरणे तो कमी करू शकतात. तुम्ही NexoChess डेटा-संमती सेटिंग्जमधून कधीही Analytics संमती मागे घेऊ शकता."
    },
    pl: {
        updated: "Ostatnia aktualizacja: 7 sierpnia 2026",
        plainSummary: "Analiza może pozostać w przeglądarce. Opcjonalne konto dodaje niezbędne pliki cookie uwierzytelniania i przechowywanie w chmurze. Jeśli wyrazisz zgodę na Analitykę, NexoChess używa także Google Analytics 4 do poznawania zagregowanego sposobu korzystania z witryny. Reklamy pozostają wyłączone.",
        dataBullet: "Opcjonalne dane analityczne po wyrażeniu zgody: adres URL i tytuł strony, statystyki sesji i użycia, przybliżona lokalizacja geograficzna, informacje o przeglądarce i urządzeniu oraz pseudonimowe identyfikatory klienta i sesji tworzone przez Google Analytics 4. NexoChess nie wysyła celowo do GA4 treści partii szachowych ani identyfikatorów konta NexoChess.",
        purposeBullet: "Mierzenie zagregowanego użycia witryny i ulepszanie NexoChess za pomocą Google Analytics 4 wyłącznie po uzyskaniu zgody na Analitykę. Pomiar reklam i personalizacja reklam pozostają na tym etapie wyłączone.",
        browserStorageParagraph: "Po zalogowaniu ściśle niezbędne pliki cookie uwierzytelniania lub równoważna pamięć sesji zabezpieczają sesję. Jeśli zezwolisz na Analitykę, Google Analytics 4 może ustawiać własne pliki cookie, takie jak _ga i _ga_<container-id>, aby rozróżniać pseudonimowych użytkowników i utrzymywać stan sesji; Google dokumentuje domyślny czas do dwóch lat, z zastrzeżeniem ograniczeń przeglądarki. Tag Google Analytics nie jest ładowany przed uzyskaniem zgody. Jeśli później wycofasz zgodę, NexoChess aktualizuje zgodę analityczną na odmowę; istniejące pliki cookie analityczne mogą pozostać do czasu ich usunięcia lub wygaśnięcia. Usunięcie plików cookie uwierzytelniania może Cię wylogować.",
        providerBullet: "Google Analytics 4 (Google): opcjonalny, oparty na zgodzie pomiar korzystania z witryny. Przechowywanie reklamowe, dane użytkownika do reklam, personalizacja reklam i Google Signals są na tym etapie wyłączone przez integrację NexoChess.",
        retentionParagraph: "Dane Google Analytics są przechowywane zgodnie z ustawieniami retencji usługi GA4 NexoChess i odpowiednimi mechanizmami Google. Własne pliki cookie GA4 mają dokumentowany przez Google domyślny okres do dwóch lat, choć zasady przeglądarki mogą go skrócić. Zgodę na Analitykę możesz wycofać w dowolnym momencie w ustawieniach zgody na dane NexoChess."
    }
};

function cloneSection(section: LegalSection | undefined): LegalSection | undefined {
    if (!section) return undefined;
    return {
        ...section,
        paragraphs: section.paragraphs ? [...section.paragraphs] : undefined,
        bullets: section.bullets ? [...section.bullets] : undefined
    };
}

function normaliseLanguage(language: string) {
    return language.toLowerCase().split("-")[0];
}

export function applyAnalyticsPrivacyRevision(
    copy: LegalDocumentCopy,
    language: string
): LegalDocumentCopy {
    const patch = patches[normaliseLanguage(language)] || patches.en;
    const sections = { ...(copy.sections || {}) };

    const dataCollected = cloneSection(sections.dataCollected);
    if (dataCollected) {
        dataCollected.bullets = [...(dataCollected.bullets || []), patch.dataBullet];
        sections.dataCollected = dataCollected;
    }

    const purposes = cloneSection(sections.purposes);
    if (purposes) {
        const bullets = purposes.bullets || [];
        purposes.bullets = bullets.length > 0
            ? [...bullets.slice(0, -1), patch.purposeBullet]
            : [patch.purposeBullet];
        sections.purposes = purposes;
    }

    const browserStorage = cloneSection(sections.browserStorage);
    if (browserStorage) {
        const paragraphs = browserStorage.paragraphs || [];
        browserStorage.paragraphs = paragraphs.length > 0
            ? [...paragraphs.slice(0, -1), patch.browserStorageParagraph]
            : [patch.browserStorageParagraph];
        sections.browserStorage = browserStorage;
    }

    const providers = cloneSection(sections.providers);
    if (providers) {
        const bullets = providers.bullets || [];
        providers.bullets = bullets.length > 0
            ? [...bullets.slice(0, -1), patch.providerBullet, ...bullets.slice(-1)]
            : [patch.providerBullet];
        sections.providers = providers;
    }

    const retention = cloneSection(sections.retention);
    if (retention) {
        retention.paragraphs = [
            ...(retention.paragraphs || []),
            patch.retentionParagraph
        ];
        sections.retention = retention;
    }

    return {
        ...copy,
        updated: patch.updated,
        plainSummary: patch.plainSummary,
        sections
    };
}
