export default {
    savedLinesTitle: "Gespeicherte Varianten",
    savedLinesHelp: "Benenne die Varianten, die du wirklich behalten willst. Sie bleiben in diesem Repertoire.",
    saveLine: "Diese Variante speichern",
    renameLine: "Variante umbenennen",
    studyLines: "Varianten üben",
    studyMixed: "Gemischtes Repertoire üben",
    studyMixedHelp: "Mischt gespeicherte Varianten aus allen persönlichen Repertoires.",
    noSavedLines: "Noch keine benannte Variante.",
    openLine: "Öffnen",
    deleteLine: "Löschen",
    deleteConfirm: "Gespeicherte Variante löschen? Die Züge bleiben im Baum erhalten.",
    saveModalTitle: "Variante speichern",
    suggestedQuestion: "Vorgeschlagener Name: „{name}“. Beibehalten?",
    linePreview: "Variante ab deiner Basis: {moves}",
    useSuggested: "Ja, Namen verwenden",
    changeName: "Namen ändern",
    customNameLabel: "Variantenname",
    customNamePlaceholder: "Zum Beispiel: Hauptabtauschvariante",
    save: "Speichern",
    cancel: "Abbrechen",
    suggestedLineName: "Variante nach {move}",
    studyTitle: "{name} üben",
    studyMixedTitle: "Gemischtes Repertoire-Training",
    studyIntro: "Spiele deine Züge aus dem Gedächtnis. Der Gegner antwortet automatisch.",
    exitStudy: "Training beenden",
    lineCounter: "Variante {current} von {total}",
    correct: "Richtig",
    wrong: "Falsch",
    correctMove: "Richtiger Zug: {move}",
    repeating: "Wir wiederholen die Variante von vorne.",
    studyComplete: "Training abgeschlossen",
    studyCompleteBody: "Du hast alle gespeicherten Varianten dieser Sitzung reproduziert.",
    nextLine: "Nächste Variante",
    coach: "Trainer",
    chooseCoach: "Trainer wählen",
    noStudyLines: "Noch nichts zu üben",
    noStudyLinesBody: "Speichere zuerst mindestens eine benannte Variante.",
    coachReady: "Du bist dran. Rekonstruiere die Variante aus dem Gedächtnis; ich spiele die Antworten des Gegners.",
    coachCorrect: "Gut. Dieser Zug gehört zur Variante. Weiter.",
    coachWrong: "Nicht dieser. Richtig ist {move}. Ich setze die Variante zurück.",
    coachOpponent: "Das ist die gespeicherte Antwort des Gegners. Bereite deinen nächsten Zug vor.",
    coachLineDone: "Gut. Ganze Variante reproduziert. Weiter zur nächsten.",
    moveProgress: "Zug {current} von {total}"
};
