export default {
    savedLinesTitle: "Saved lines",
    savedLinesHelp: "Name the branches you actually want to remember. They stay inside this repertoire.",
    saveLine: "Save this line",
    renameLine: "Rename saved line",
    studyLines: "Study saved lines",
    studyMixed: "Study mixed repertoire",
    studyMixedHelp: "Mix saved lines from all your personal repertoires in one session.",
    noSavedLines: "You have not named any line yet.",
    openLine: "Open",
    deleteLine: "Delete",
    deleteConfirm: "Delete this saved line? The chess moves will remain in the move tree.",
    saveModalTitle: "Save this line",
    suggestedQuestion: "Suggested name: “{name}”. Do you want to keep it?",
    linePreview: "Line from your base: {moves}",
    useSuggested: "Yes, use this name",
    changeName: "Change name",
    customNameLabel: "Line name",
    customNamePlaceholder: "For example: Main exchange line",
    save: "Save line",
    cancel: "Cancel",
    suggestedLineName: "Line after {move}",
    studyTitle: "Study {name}",
    studyMixedTitle: "Mixed repertoire study",
    studyIntro: "Play your moves from memory. The opponent replies automatically.",
    exitStudy: "Exit study",
    lineCounter: "Line {current} of {total}",
    correct: "Correct",
    wrong: "Wrong",
    correctMove: "Correct move: {move}",
    repeating: "We repeat the line from the beginning.",
    studyComplete: "Session complete",
    studyCompleteBody: "You reproduced every saved line in this session.",
    nextLine: "Next line",
    coach: "Coach",
    chooseCoach: "Choose coach",
    noStudyLines: "Nothing to study yet",
    noStudyLinesBody: "Save at least one named line in a personal repertoire first.",
    coachReady: "Your turn. Rebuild the line from memory and I will handle the opponent's replies.",
    coachCorrect: "Good. That move belongs to the line. Keep going.",
    coachWrong: "Not that one. The correct move is {move}. I will reset the line so you can repeat it.",
    coachOpponent: "This is the opponent's stored reply. Watch it and prepare your next move.",
    coachLineDone: "Good. You reproduced the whole line. We move to the next one.",
    moveProgress: "Move {current} of {total}"
};
