export default {
    savedLinesTitle: "Líneas guardadas",
    savedLinesHelp: "Pon nombre a las ramas que de verdad quieres recordar. Se quedan dentro de este repertorio.",
    saveLine: "Guardar esta línea",
    renameLine: "Renombrar línea guardada",
    studyLines: "Estudiar líneas guardadas",
    studyMixed: "Estudiar repertorio mezclado",
    studyMixedHelp: "Mezcla en una sola sesión las líneas guardadas de todos tus repertorios personales.",
    noSavedLines: "Todavía no has puesto nombre a ninguna línea.",
    openLine: "Abrir",
    deleteLine: "Eliminar",
    deleteConfirm: "¿Eliminar esta línea guardada? Las jugadas seguirán existiendo en el árbol.",
    saveModalTitle: "Guardar esta línea",
    suggestedQuestion: "Nombre sugerido: «{name}». ¿Quieres dejarlo así?",
    linePreview: "Línea desde tu base: {moves}",
    useSuggested: "Sí, usar este nombre",
    changeName: "Cambiar nombre",
    customNameLabel: "Nombre de la línea",
    customNamePlaceholder: "Por ejemplo: Línea principal de cambios",
    save: "Guardar línea",
    cancel: "Cancelar",
    suggestedLineName: "Línea tras {move}",
    studyTitle: "Estudiar {name}",
    studyMixedTitle: "Estudio mezclado del repertorio",
    studyIntro: "Juega tus movimientos de memoria. El rival responderá automáticamente.",
    exitStudy: "Salir del estudio",
    lineCounter: "Línea {current} de {total}",
    correct: "Correcta",
    wrong: "Incorrecta",
    correctMove: "Jugada correcta: {move}",
    repeating: "Repetimos la línea desde el principio.",
    studyComplete: "Sesión completada",
    studyCompleteBody: "Has reproducido todas las líneas guardadas de esta sesión.",
    nextLine: "Siguiente línea",
    coach: "Entrenador",
    chooseCoach: "Elegir entrenador",
    noStudyLines: "Todavía no hay nada que estudiar",
    noStudyLinesBody: "Guarda al menos una línea con nombre dentro de un repertorio personal.",
    coachReady: "Tu turno. Reconstruye la línea de memoria y yo haré las respuestas del rival.",
    coachCorrect: "Bien. Esa jugada pertenece a la línea. Sigue.",
    coachWrong: "Esa no. La correcta es {move}. Reinicio la línea para que la repitas.",
    coachOpponent: "Esta es la respuesta guardada del rival. Mírala y prepara tu siguiente jugada.",
    coachLineDone: "Bien. Has reproducido la línea completa. Pasamos a la siguiente.",
    moveProgress: "Jugada {current} de {total}"
};
