export default {
    savedLinesTitle: "Lignes enregistrées",
    savedLinesHelp: "Nommez les variantes que vous voulez vraiment retenir. Elles restent dans ce répertoire.",
    saveLine: "Enregistrer cette ligne",
    renameLine: "Renommer la ligne",
    studyLines: "Étudier les lignes",
    studyMixed: "Étudier le répertoire mélangé",
    studyMixedHelp: "Mélange les lignes enregistrées de tous vos répertoires personnels.",
    noSavedLines: "Aucune ligne nommée pour le moment.",
    openLine: "Ouvrir",
    deleteLine: "Supprimer",
    deleteConfirm: "Supprimer cette ligne enregistrée ? Les coups resteront dans l'arbre.",
    saveModalTitle: "Enregistrer cette ligne",
    suggestedQuestion: "Nom suggéré : « {name} ». Le garder ?",
    linePreview: "Ligne depuis votre base : {moves}",
    useSuggested: "Oui, garder ce nom",
    changeName: "Changer le nom",
    customNameLabel: "Nom de la ligne",
    customNamePlaceholder: "Par exemple : Ligne principale d'échange",
    save: "Enregistrer",
    cancel: "Annuler",
    suggestedLineName: "Ligne après {move}",
    studyTitle: "Étudier {name}",
    studyMixedTitle: "Étude mélangée du répertoire",
    studyIntro: "Jouez vos coups de mémoire. L'adversaire répond automatiquement.",
    exitStudy: "Quitter l'étude",
    lineCounter: "Ligne {current} sur {total}",
    correct: "Correct",
    wrong: "Incorrect",
    correctMove: "Bon coup : {move}",
    repeating: "On recommence la ligne depuis le début.",
    studyComplete: "Session terminée",
    studyCompleteBody: "Vous avez reproduit toutes les lignes enregistrées de cette session.",
    nextLine: "Ligne suivante",
    coach: "Coach",
    chooseCoach: "Choisir le coach",
    noStudyLines: "Rien à étudier pour le moment",
    noStudyLinesBody: "Enregistrez d'abord au moins une ligne nommée.",
    coachReady: "À vous. Reconstruisez la ligne de mémoire, je jouerai les réponses adverses.",
    coachCorrect: "Bien. Ce coup appartient à la ligne. Continuez.",
    coachWrong: "Pas celui-là. Le bon coup est {move}. Je remets la ligne au début.",
    coachOpponent: "Voici la réponse enregistrée de l'adversaire. Préparez votre prochain coup.",
    coachLineDone: "Bien. Ligne complète reproduite. Passons à la suivante.",
    moveProgress: "Coup {current} sur {total}"
};
