export default {
    savedLinesTitle: "Linhas guardadas",
    savedLinesHelp: "Dê nome às variantes que realmente quer memorizar. Elas ficam dentro deste repertório.",
    saveLine: "Guardar esta linha",
    renameLine: "Renomear linha",
    studyLines: "Estudar linhas guardadas",
    studyMixed: "Estudar repertório misto",
    studyMixedHelp: "Mistura linhas guardadas de todos os seus repertórios pessoais.",
    noSavedLines: "Ainda não há nenhuma linha com nome.",
    openLine: "Abrir",
    deleteLine: "Eliminar",
    deleteConfirm: "Eliminar esta linha guardada? Os lances continuarão na árvore.",
    saveModalTitle: "Guardar esta linha",
    suggestedQuestion: "Nome sugerido: “{name}”. Quer mantê-lo?",
    linePreview: "Linha desde a sua base: {moves}",
    useSuggested: "Sim, usar este nome",
    changeName: "Mudar nome",
    customNameLabel: "Nome da linha",
    customNamePlaceholder: "Por exemplo: Linha principal de trocas",
    save: "Guardar linha",
    cancel: "Cancelar",
    suggestedLineName: "Linha após {move}",
    studyTitle: "Estudar {name}",
    studyMixedTitle: "Estudo misto do repertório",
    studyIntro: "Jogue os seus lances de memória. O adversário responderá automaticamente.",
    exitStudy: "Sair do estudo",
    lineCounter: "Linha {current} de {total}",
    correct: "Correto",
    wrong: "Errado",
    correctMove: "Lance correto: {move}",
    repeating: "Vamos repetir a linha desde o início.",
    studyComplete: "Sessão concluída",
    studyCompleteBody: "Você reproduziu todas as linhas guardadas desta sessão.",
    nextLine: "Próxima linha",
    coach: "Treinador",
    chooseCoach: "Escolher treinador",
    noStudyLines: "Ainda não há nada para estudar",
    noStudyLinesBody: "Guarde primeiro pelo menos uma linha com nome.",
    coachReady: "Sua vez. Reconstrua a linha de memória e eu farei as respostas do adversário.",
    coachCorrect: "Bem. Esse lance pertence à linha. Continue.",
    coachWrong: "Esse não. O correto é {move}. Vou reiniciar a linha para você repeti-la.",
    coachOpponent: "Esta é a resposta guardada do adversário. Prepare o próximo lance.",
    coachLineDone: "Bem. Linha completa reproduzida. Vamos à próxima.",
    moveProgress: "Lance {current} de {total}"
};
