export default {
    savedLinesTitle: "Сохранённые варианты",
    savedLinesHelp: "Давайте названия вариантам, которые действительно хотите запомнить. Они останутся в этом репертуаре.",
    saveLine: "Сохранить вариант",
    renameLine: "Переименовать вариант",
    studyLines: "Тренировать варианты",
    studyMixed: "Смешанная тренировка",
    studyMixedHelp: "Смешивает сохранённые варианты из всех личных репертуаров.",
    noSavedLines: "Пока нет именованных вариантов.",
    openLine: "Открыть",
    deleteLine: "Удалить",
    deleteConfirm: "Удалить сохранённый вариант? Ходы останутся в дереве.",
    saveModalTitle: "Сохранить вариант",
    suggestedQuestion: "Предлагаемое имя: «{name}». Оставить его?",
    linePreview: "Вариант от базовой позиции: {moves}",
    useSuggested: "Да, оставить имя",
    changeName: "Изменить имя",
    customNameLabel: "Название варианта",
    customNamePlaceholder: "Например: Главный разменный вариант",
    save: "Сохранить",
    cancel: "Отмена",
    suggestedLineName: "Вариант после {move}",
    studyTitle: "Тренировка: {name}",
    studyMixedTitle: "Смешанная тренировка репертуара",
    studyIntro: "Воспроизводите свои ходы по памяти. Соперник отвечает автоматически.",
    exitStudy: "Выйти",
    lineCounter: "Вариант {current} из {total}",
    correct: "Верно",
    wrong: "Неверно",
    correctMove: "Правильный ход: {move}",
    repeating: "Повторяем вариант с начала.",
    studyComplete: "Тренировка завершена",
    studyCompleteBody: "Вы воспроизвели все сохранённые варианты этой сессии.",
    nextLine: "Следующий вариант",
    coach: "Тренер",
    chooseCoach: "Выбрать тренера",
    noStudyLines: "Пока нечего тренировать",
    noStudyLinesBody: "Сначала сохраните хотя бы один именованный вариант.",
    coachReady: "Ваш ход. Восстановите вариант по памяти, а я сыграю ответы соперника.",
    coachCorrect: "Хорошо. Этот ход входит в вариант. Продолжайте.",
    coachWrong: "Не этот. Правильный ход — {move}. Начинаем вариант заново.",
    coachOpponent: "Это сохранённый ответ соперника. Подготовьте следующий ход.",
    coachLineDone: "Хорошо. Вариант воспроизведён полностью. Переходим дальше.",
    moveProgress: "Ход {current} из {total}"
};
