export default {
    savedLinesTitle: "Các biến đã lưu",
    savedLinesHelp: "Đặt tên cho những nhánh bạn thật sự muốn nhớ. Chúng ở lại trong repertoire này.",
    saveLine: "Lưu biến này",
    renameLine: "Đổi tên biến",
    studyLines: "Luyện các biến đã lưu",
    studyMixed: "Luyện repertoire trộn",
    studyMixedHelp: "Trộn các biến đã lưu từ mọi repertoire cá nhân trong một buổi.",
    noSavedLines: "Chưa có biến nào được đặt tên.",
    openLine: "Mở",
    deleteLine: "Xóa",
    deleteConfirm: "Xóa biến đã lưu này? Các nước vẫn còn trong cây nước đi.",
    saveModalTitle: "Lưu biến này",
    suggestedQuestion: "Tên gợi ý: “{name}”. Giữ tên này?",
    linePreview: "Biến từ vị trí gốc của bạn: {moves}",
    useSuggested: "Có, dùng tên này",
    changeName: "Đổi tên",
    customNameLabel: "Tên biến",
    customNamePlaceholder: "Ví dụ: Biến đổi quân chính",
    save: "Lưu biến",
    cancel: "Hủy",
    suggestedLineName: "Biến sau {move}",
    studyTitle: "Luyện {name}",
    studyMixedTitle: "Luyện repertoire trộn",
    studyIntro: "Đi các nước của bạn bằng trí nhớ. Đối thủ sẽ tự động đáp lại.",
    exitStudy: "Thoát luyện tập",
    lineCounter: "Biến {current}/{total}",
    correct: "Đúng",
    wrong: "Sai",
    correctMove: "Nước đúng: {move}",
    repeating: "Lặp lại biến từ đầu.",
    studyComplete: "Hoàn thành buổi luyện",
    studyCompleteBody: "Bạn đã tái hiện mọi biến đã lưu trong buổi này.",
    nextLine: "Biến tiếp theo",
    coach: "Huấn luyện viên",
    chooseCoach: "Chọn huấn luyện viên",
    noStudyLines: "Chưa có gì để luyện",
    noStudyLinesBody: "Trước tiên hãy lưu ít nhất một biến có tên.",
    coachReady: "Đến lượt bạn. Hãy dựng lại biến bằng trí nhớ, tôi sẽ đi các nước của đối thủ.",
    coachCorrect: "Tốt. Nước đó nằm trong biến. Tiếp tục.",
    coachWrong: "Không phải nước đó. Nước đúng là {move}. Tôi sẽ đặt lại biến để bạn lặp lại.",
    coachOpponent: "Đây là phản hồi đã lưu của đối thủ. Chuẩn bị nước tiếp theo.",
    coachLineDone: "Tốt. Bạn đã hoàn thành cả biến. Sang biến tiếp theo.",
    moveProgress: "Nước {current}/{total}"
};
