export default {
    savedLinesTitle: "已保存路线",
    savedLinesHelp: "给真正想记住的分支命名。它们会保留在这个个人棋谱中。",
    saveLine: "保存这条路线",
    renameLine: "重命名路线",
    studyLines: "练习已保存路线",
    studyMixed: "混合练习个人棋谱",
    studyMixedHelp: "把所有个人棋谱中的已保存路线混在一次训练中。",
    noSavedLines: "还没有命名的路线。",
    openLine: "打开",
    deleteLine: "删除",
    deleteConfirm: "删除这条已保存路线？走法仍会保留在走法树中。",
    saveModalTitle: "保存这条路线",
    suggestedQuestion: "建议名称：“{name}”。是否使用？",
    linePreview: "从基础位置开始的路线：{moves}",
    useSuggested: "是，使用该名称",
    changeName: "修改名称",
    customNameLabel: "路线名称",
    customNamePlaceholder: "例如：主交换路线",
    save: "保存路线",
    cancel: "取消",
    suggestedLineName: "{move} 后的路线",
    studyTitle: "练习 {name}",
    studyMixedTitle: "混合个人棋谱训练",
    studyIntro: "凭记忆走自己的棋。对手会自动回应。",
    exitStudy: "退出训练",
    lineCounter: "路线 {current}/{total}",
    correct: "正确",
    wrong: "错误",
    correctMove: "正确走法：{move}",
    repeating: "从头重复这条路线。",
    studyComplete: "训练完成",
    studyCompleteBody: "你已经复现了本次训练中的所有已保存路线。",
    nextLine: "下一条路线",
    coach: "教练",
    chooseCoach: "选择教练",
    noStudyLines: "暂时没有可练习内容",
    noStudyLinesBody: "请先在个人棋谱中保存至少一条命名路线。",
    coachReady: "轮到你了。凭记忆重建路线，我会走对手的回应。",
    coachCorrect: "很好。这步属于路线，继续。",
    coachWrong: "不是这步。正确走法是 {move}。我会重置路线让你再来一次。",
    coachOpponent: "这是已保存的对手回应。准备你的下一步。",
    coachLineDone: "很好。整条路线已复现，进入下一条。",
    moveProgress: "走法 {current}/{total}"
};
